# fly.toml app configuration file generated for up-sell-app on 2023-10-06T14:30:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "up-sell-app"
primary_region = "iad"

[build]

[env]
  PORT = 8081
  SCOPES = "write_products, read_files, write_files, read_metaobjects, write_metaobjects, write_metaobject_definitions"
  SHOPIFY_API_KEY = "09643a1debbb2d6bfed9ceb384df5523"
  SHOPIFY_APP_URL = "https://up-sell-app.fly.dev"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
